# set of authorizers
authorizers:
    - "cabin scare gold claim ill term scissors rigid drill quick where wisdom"
    - "accident claw bulb broken hold marine prefer drum talk rice insane cake"
    - "road super range nephew cancel bulb kite spell reveal bonus universe clown"
    - "vague vault achieve crush useful ceiling exhibit just chat message net arch"
    - "stadium scrap hero broom soccer horse combine erase detail minute virtual belt"
    - "coconut moral level thing soldier excess ranch swim balance magnet embrace beef"