#block_worker: https://cube.devnet-0chain.net/dns # to debug in container
#signature_scheme: "bls0chain"
#min_submit: 50 # in percentage
#min_confirmation: 50 # in percentage
#confirmation_chain_length: 3

bridge:
    loglevel: "debug"
    # Address of Ethereum bridge contract
    BridgeAddress: "0xF26B52df8c6D9b9C20bfD7819Bed75a75258c7dB"
    # Address of Ethereum authorizers contract
    AuthorizersAddress: "0xFE20Ce9fBe514397427d20C91CB657a4478A0FFa"
    # User's ethereum wallet mnemonic
    # Address: 0x29C819651c4aE22Aba0B36bf8D4805daBaAa49F7
    ClientEthereumMnemonic: "praise portion right again neglect frog border inch spatial nerve program wet"
    OwnerEthereumMnemonic: "add here the owner mnemonic that has deployed auth and bridge contracts"
    # Address of WZCN token (Example: https://ropsten.etherscan.io/token/0x930E1BE76461587969Cb7eB9BFe61166b1E70244)
    WzcnAddress: "0x930E1BE76461587969Cb7eB9BFe61166b1E70244"
    # URL of ethereum RPC node (infura or alchemy)
    EthereumNodeURL: "https://ropsten.infura.io/v3/22cb2849f5f74b8599f3dc2a23085bd4"
    # Gas limit to execute ethereum transaction
    GasLimit: 300000
    ChainID: "3"
    # Value to execute ZCN smart contracts in wei
    Value: 0
    ConsensusThreshold: 70.0
