bridge:
    Password: password
    EthereumAddress: 0x860FA46F170a87dF44D7bB867AA4a5D2813127c1
    BridgeAddress: 0xF26B52df8c6D9b9C20bfD7819Bed75a75258c7dB
    WzcnAddress: 0x930E1BE76461587969Cb7eB9BFe61166b1E70244
    AuthorizersAddress: 0xFE20Ce9fBe514397427d20C91CB657a4478A0FFa
    EthereumNodeURL: https://ropsten.infura.io/v3/22cb2849f5f74b8599f3dc2a23085bd4
    GasLimit: 300000
    Value: 0
