name: TRIGGER_ZBOXCLI

on:
  workflow_dispatch:
    inputs:
      branch_ref:
        description: 'Input branch of zboxcli to build'
        required: true
      fixed_tag:
        description: 'Type yes For Building With Tag v0.0.0 from master & v1.1.1 from staging'
        default: 'no'
        required: true
      version_tag:
        description: 'Input major or miner for release type. Default is patch'
        default: 'patch'
        required: true

jobs:
  zboxcli:
    name: Triggering zboxcli Build
    runs-on: [self-hosted, build]
    
    steps:
    - name: Generating JSON for Input
      id: get_tag
      run: |
          JSON=$(echo {\"fixed_tag\":\"$TAG\"\,\"version_tag\":\"$VERSION_TAG\"})
          echo ::set-output name=JSON::${JSON}
      env:
        TAG: ${{ github.event.inputs.fixed_tag }}
        VERSION_TAG: ${{ github.event.inputs.version_tag }}

    - name: Triggering zboxcli Build
      uses: convictional/trigger-workflow-and-wait@v1.3.0
      with:
        owner: 0chain
        repo: zboxcli
        github_token: ${{ secrets.GOSDK }}
        workflow_file_name: build-zboxcli.yml
        ref: ${{ github.event.inputs.branch_ref }}
        inputs: ${{ steps.get_tag.outputs.JSON }}
        propagate_failure: true
        trigger_workflow: true
        wait_workflow: true

    - name: Completing Trigger
      run: |
        echo "Tag ${TAG}."
        BRANCH=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')
        SHORT_SHA=$(echo $GITHUB_SHA | head -c 8)
      env:
        TAG: ${{ github.event.inputs.fixed_tag }}
        VERSION_TAG: ${{ github.event.inputs.version_tag }}
