name: TRIGGER_ZWALLETCLI

on:
  workflow_dispatch:
    inputs:
      branch_ref:
        description: 'Input branch of zwalletcli to build'
        required: true
      fixed_tag:
        description: 'Type yes For Building With Tag v0.0.0 from master & v1.1.1 from staging'
        default: 'no'
        required: true
      version_tag:
        description: 'Input Tag Example - v1.2.2'
        required: true
jobs:        
  zwalletcli:
    name: Triggering zwalletcli Build
    runs-on: ubuntu-20.04
    
    steps:
    - name: Generating JSON for Input
      id: get_tag
      run: |
          JSON=$(echo {\"latest_tag\":\"$TAG\"})
          echo ::set-output name=JSON::${JSON}
      env:
        TAG: ${{ github.event.inputs.latest_tag }}
        
    - name: Triggering zwalletcli Build
      uses: convictional/trigger-workflow-and-wait@v1.3.0
      with:
        owner: 0chain
        repo: zwalletcli
        github_token: ${{ secrets.GOSDK }}
        workflow_file_name: build-zwalletcli.yml
        ref: ${{ github.event.inputs.branch_ref }} 
        fixed_tag: ${{ github.event.inputs.fixed_tag }}
        inputs: ${{ steps.get_tag.outputs.JSON }}
        propagate_failure: true
        trigger_workflow: true
        wait_workflow: true

    - name: Completing Trigger
      run: |
        echo "Tag ${TAG}."
        BRANCH=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')
        SHORT_SHA=$(echo $GITHUB_SHA | head -c 8)
      env:
        TAG: ${{ github.event.inputs.latest_tag }}